# Generated by Django 2.0.4 on 2018-05-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180507_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Angliya',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Asia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Avstraliya',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='China',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='SHA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Shengen',
            field=models.BooleanField(default=False),
        ),
    ]
