# Generated by Django 2.0.4 on 2018-04-22 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromLoc', models.CharField(max_length=200)),
                ('toLoc', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('go_date', models.DateTimeField()),
            ],
        ),
    ]
