# Generated by Django 2.0.4 on 2018-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_remove_infotour_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotour',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
            preserve_default=False,
        ),
    ]
