# Generated by Django 2.0.4 on 2018-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_infotour_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infotour',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='infotour',
            name='json1',
            field=models.CharField(default={'lol': 'kek'}, max_length=200),
            preserve_default=False,
        ),
    ]
