# Generated by Django 2.0.4 on 2018-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0005_remove_infotour_json1'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotour',
            name='json1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
