# Generated by Django 2.0.4 on 2018-05-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0007_auto_20180517_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotour',
            name='Adress1',
            field=models.CharField(default='', max_length=200, verbose_name='адрес отправки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infotour',
            name='Adress2',
            field=models.CharField(default='', max_length=200, verbose_name='адрес прибытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infotour',
            name='back_date',
            field=models.DateTimeField(default='2019-01-01', verbose_name='Время возвращения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infotour',
            name='fromLoc',
            field=models.CharField(max_length=200, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='infotour',
            name='go_date',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='infotour',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='infotour',
            name='toLoc',
            field=models.CharField(max_length=200, verbose_name='Город назначения'),
        ),
    ]
