# Generated by Django 2.0.4 on 2018-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0008_auto_20180518_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotour',
            name='Adress1',
            field=models.CharField(max_length=200, verbose_name='адрес отбытия'),
        ),
    ]
