# Generated by Django 2.0.4 on 2018-05-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0009_auto_20180520_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infotour',
            options={'verbose_name': 'Билеты'},
        ),
    ]
