# Generated by Django 2.0.4 on 2018-05-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0010_auto_20180524_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infotour',
            options={'verbose_name': 'Билеты', 'verbose_name_plural': 'Билеты'},
        ),
    ]
