# Generated by Django 2.0.4 on 2018-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=30)),
                ('country', models.TextField(max_length=30)),
                ('idCoun', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
