# Generated by Django 2.0.4 on 2018-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='photo',
            field=models.ImageField(upload_to='static/images/', verbose_name='Изображение'),
        ),
    ]
