# Generated by Django 2.0.4 on 2018-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0002_auto_20180515_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='photo',
            field=models.ImageField(upload_to='recomend/static/images/recomend', verbose_name='Изображение'),
        ),
    ]
