# Generated by Django 2.0.4 on 2018-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0003_auto_20180515_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='photo',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение'),
        ),
    ]
