# Generated by Django 2.0.4 on 2018-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0004_auto_20180515_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reklama',
            options={'verbose_name': 'Рекламные туры', 'verbose_name_plural': 'Рекламные туры'},
        ),
    ]
