# Generated by Django 2.0.4 on 2018-05-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_auto_20180511_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vises',
            old_name='nameRu',
            new_name='nameEng',
        ),
        migrations.RemoveField(
            model_name='vises',
            name='visaType',
        ),
        migrations.RemoveField(
            model_name='vises',
            name='visqIs',
        ),
    ]
