# Generated by Django 2.0.4 on 2018-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_auto_20180511_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vises',
            name='nameShort',
            field=models.CharField(max_length=200, verbose_name='Страна short'),
        ),
    ]
