# Generated by Django 2.0.4 on 2018-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0004_auto_20180511_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('en', models.CharField(max_length=30, verbose_name='Название на англ')),
                ('ru', models.CharField(max_length=30, verbose_name='Название на русском')),
                ('country_code', models.CharField(max_length=10, verbose_name='Код страны')),
                ('code', models.CharField(max_length=10, verbose_name='Код города')),
            ],
        ),
    ]
