# Generated by Django 2.0.4 on 2018-05-21 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exc', '0002_excursions_pricetra'),
        ('Tour', '0009_auto_20180520_1340'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='Конечная стоимость')),
                ('kolvo_people', models.IntegerField(verbose_name='Кол-во пасажиров')),
                ('exc', models.TextField(verbose_name='Экскурсии')),
                ('tickets', models.TextField(verbose_name='Билеты')),
                ('hotel', models.CharField(max_length=200, verbose_name='Название отеля')),
                ('obj_exc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exc.excursions')),
                ('obj_tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.InfoTour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
