# Generated by Django 2.0.4 on 2018-05-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20180521_1439'),
        ('buy_tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='obj_exc',
        ),
        migrations.AddField(
            model_name='tour',
            name='obj_hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel', verbose_name='отель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='exc',
            field=models.TextField(verbose_name='Экскурсия'),
        ),
    ]
