# Generated by Django 2.0.4 on 2018-05-21 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_tour', '0002_auto_20180521_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
