# Generated by Django 2.0.4 on 2018-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_tour', '0003_auto_20180522_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Купленные туры', 'verbose_name_plural': 'Купленные туры'},
        ),
    ]
