# Generated by Django 2.0.4 on 2018-05-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEng', models.CharField(max_length=200, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa', models.CharField(max_length=100, verbose_name='Тип визы')),
                ('days', models.IntegerField(verbose_name='Въезд на n дней')),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_visa_set', to='counryVisa.Country')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_visa_set', to='counryVisa.Country')),
            ],
        ),
    ]
