# Generated by Django 2.0.4 on 2018-05-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counryVisa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='from_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_visa_set', to='counryVisa.Country'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='to_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_visa_set', to='counryVisa.Country'),
        ),
    ]
