# Generated by Django 2.0.4 on 2018-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counryVisa', '0002_auto_20180512_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='document',
            field=models.TextField(default='Не надо', verbose_name='Документы для визы'),
        ),
        migrations.AddField(
            model_name='country',
            name='nameVisa',
            field=models.CharField(default='', max_length=200, verbose_name='Название визы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='price',
            field=models.IntegerField(default=50, verbose_name='цена визы в $'),
        ),
        migrations.AddField(
            model_name='country',
            name='term_tourism',
            field=models.CharField(default='', max_length=200, verbose_name='Срок изготовление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visa',
            name='days',
            field=models.CharField(max_length=100, verbose_name='дней без визы'),
        ),
    ]
