# Generated by Django 2.0.4 on 2018-05-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counryVisa', '0003_auto_20180513_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='document2',
            field=models.TextField(default='Не надо', verbose_name='Документы для визы'),
        ),
        migrations.AddField(
            model_name='country',
            name='document3',
            field=models.TextField(default='Не надо', verbose_name='Документы для визы'),
        ),
        migrations.AddField(
            model_name='country',
            name='nameVisa2',
            field=models.CharField(default='', max_length=200, verbose_name='Название визы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='nameVisa3',
            field=models.CharField(default='', max_length=200, verbose_name='Название визы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='price2',
            field=models.IntegerField(default=50, verbose_name='цена визы в $'),
        ),
        migrations.AddField(
            model_name='country',
            name='price3',
            field=models.IntegerField(default=50, verbose_name='цена визы в $'),
        ),
        migrations.AddField(
            model_name='country',
            name='term_tourism2',
            field=models.CharField(default='', max_length=200, verbose_name='Срок изготовление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='term_tourism3',
            field=models.CharField(default='', max_length=200, verbose_name='Срок изготовление'),
            preserve_default=False,
        ),
    ]
