# Generated by Django 2.0.4 on 2018-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counryVisa', '0007_auto_20180524_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='for_buy_prigl',
            field=models.BooleanField(default=True, verbose_name='Покупка. Справка с места работы'),
        ),
    ]
