# Generated by Django 2.0.4 on 2018-05-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counryVisa', '0008_auto_20180524_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='for_buy_rab',
            field=models.BooleanField(default=True, verbose_name='Покупка. Справка с места работы'),
        ),
        migrations.AlterField(
            model_name='country',
            name='for_buy_prigl',
            field=models.BooleanField(default=False, verbose_name='Покупка. Приглашение'),
        ),
    ]
