# Generated by Django 2.0.4 on 2018-05-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counryVisa', '0010_auto_20180524_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='for_buy_iin',
        ),
        migrations.RemoveField(
            model_name='country',
            name='for_buy_pas',
        ),
        migrations.RemoveField(
            model_name='country',
            name='for_buy_zag',
        ),
    ]
