# Generated by Django 2.0.4 on 2018-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCity', models.CharField(max_length=200, verbose_name='Город в котором находится отель')),
                ('opicanie', models.TextField(verbose_name='Описание')),
                ('food', models.BooleanField(default=False, verbose_name='Входит ли еда')),
                ('kolvo', models.IntegerField(default=150, verbose_name='Кол-во свободных мест')),
                ('price_one_pers_day', models.IntegerField(default=500)),
                ('photo', models.ImageField(upload_to='image/', verbose_name='Изображение')),
            ],
        ),
    ]
