# Generated by Django 2.0.4 on 2018-05-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='nameOtel',
            field=models.CharField(default='', max_length=200, verbose_name='Город в котором находится отель'),
            preserve_default=False,
        ),
    ]
