# Generated by Django 2.0.4 on 2018-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20180521_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отели', 'verbose_name_plural': 'Отели'},
        ),
    ]
