# Generated by Django 2.0.4 on 2018-05-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='priceTRa',
            field=models.IntegerField(default=200, verbose_name='Стоимость трансфера'),
            preserve_default=False,
        ),
    ]
