# Generated by Django 2.0.4 on 2018-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exc', '0002_excursions_pricetra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursions',
            options={'verbose_name': 'Экскурсии', 'verbose_name_plural': 'Экскурсии'},
        ),
    ]
